"""
Seed script: Tambah template assessment KN3 ERP Discovery ke KBS.
14 domain, ~85 pertanyaan tentang ERP & RFID untuk perusahaan tekstil/distribusi.
"""
import asyncio
import os
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient

MONGO_URL = os.environ.get("MONGO_URL", "mongodb://localhost:27017")
DB_NAME = os.environ.get("DB_NAME", "test_database")

OTHER_SENTINEL = "__other__"
OTHER_LABEL = "Lainnya (isi sendiri)"

KN3_TEMPLATE = {
    "id": "kn3-erp-discovery-v1",
    "name": {"id": "ERP & RFID Discovery Questionnaire", "en": "ERP & RFID Discovery Questionnaire"},
    "description": {
        "id": "Kuesioner discovery untuk kebutuhan implementasi ERP & RFID pada perusahaan distribusi tekstil. 14 domain, ~85 pertanyaan.",
        "en": "Discovery questionnaire for ERP & RFID implementation needs in textile distribution companies."
    },
    "version": "1.0",
    "is_published": True,
    "estimated_minutes": 180,
    "created_at": datetime.now(timezone.utc).isoformat(),
    "updated_at": datetime.now(timezone.utc).isoformat(),
    "domains": [
        {
            "id": "D01",
            "number": 1,
            "code": "company-profile",
            "title": {"id": "Profil Perusahaan & Tujuan Strategis", "en": "Company Profile & Strategic Goals"},
            "icon": "Building2",
            "color": "blue",
            "recommended_pic": ["CEO / Owner", "Direktur Utama"],
            "estimated_minutes": 15,
            "description": {"id": "Memahami profil bisnis, ukuran perusahaan, dan target strategis 3-5 tahun ke depan agar ERP yang dibangun sesuai konteks bisnis Anda.", "en": "Understanding business profile and strategic targets."},
            "questions": [
                {
                    "id": "D01-Q01",
                    "prompt": {"id": "Jenis bisnis utama perusahaan?", "en": "Main business type?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "distributor", "label": "Distributor / Wholesaler"},
                        {"value": "retailer", "label": "Retailer (B2C)"},
                        {"value": "hybrid", "label": "Hybrid (Wholesale + Retail)"},
                        {"value": "trading", "label": "Trading Company (import/export)"},
                    ],
                    "help": {"id": "Pilih yang paling mendekati. Ini menentukan modul mana yang jadi prioritas.", "en": "Choose the closest match."},
                },
                {
                    "id": "D01-Q02",
                    "prompt": {"id": "Berapa total karyawan saat ini?", "en": "Total number of employees?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "1-25", "label": "1 – 25 orang"},
                        {"value": "26-50", "label": "26 – 50 orang"},
                        {"value": "51-100", "label": "51 – 100 orang"},
                        {"value": "101-250", "label": "101 – 250 orang"},
                        {"value": "251+", "label": "Lebih dari 250 orang"},
                    ],
                    "help": {"id": "Hitung total karyawan tetap + kontrak.", "en": "Include permanent and contract employees."},
                },
                {
                    "id": "D01-Q03",
                    "prompt": {"id": "Berapa jumlah lokasi operasional (kantor + gudang + toko)?", "en": "Number of operational locations?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "1", "label": "1 lokasi (terpusat)"},
                        {"value": "2-3", "label": "2 – 3 lokasi"},
                        {"value": "4-10", "label": "4 – 10 lokasi"},
                        {"value": "10+", "label": "Lebih dari 10 lokasi"},
                    ],
                    "help": {"id": "Jumlah lokasi fisik yang aktif beroperasi.", "en": "Number of active physical locations."},
                },
                {
                    "id": "D01-Q04",
                    "prompt": {"id": "Apakah bagian dari group perusahaan / punya anak perusahaan?", "en": "Part of a company group or have subsidiaries?"},
                    "type": "yes_no",
                    "help": {"id": "Group structure mempengaruhi apakah ERP harus mendukung multi-entity.", "en": "Group structure affects multi-entity support needs."},
                },
                {
                    "id": "D01-Q05",
                    "prompt": {"id": "Target pertumbuhan revenue dalam 3 tahun ke depan?", "en": "Revenue growth target in 3 years?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "stable", "label": "Stabil (pertumbuhan < 10%/tahun)"},
                        {"value": "moderate", "label": "Moderat (10 – 30%/tahun)"},
                        {"value": "aggressive", "label": "Agresif (30 – 100%/tahun)"},
                        {"value": "explosive", "label": "Sangat agresif (> 100%/tahun)"},
                    ],
                    "help": {"id": "Target pertumbuhan menentukan arsitektur skalabilitas sistem.", "en": "Growth target determines system scalability architecture."},
                },
                {
                    "id": "D01-Q06",
                    "prompt": {"id": "Apa 3 tujuan utama dari investasi ERP & RFID ini? (pilih maksimal 3)", "en": "Top 3 goals for ERP & RFID investment? (max 3)"},
                    "type": "multi_choice",
                    "max_select": 3,
                    "options": [
                        {"value": "stock_accuracy", "label": "Akurasi stok > 99%"},
                        {"value": "scalability", "label": "Skalabilitas tanpa nambah headcount banyak"},
                        {"value": "real_time", "label": "Real-time visibility & faster decision"},
                        {"value": "cost_reduction", "label": "Cost reduction (efisiensi operasional)"},
                        {"value": "compliance", "label": "Compliance & audit readiness"},
                        {"value": "customer_service", "label": "Customer service level meningkat"},
                        {"value": "integration", "label": "Integrasi e-commerce / omnichannel"},
                        {"value": "automation", "label": "Otomatisasi proses manual"},
                    ],
                    "help": {"id": "Fokus pada tujuan paling kritis — ini jadi success criteria proyek.", "en": "Focus on most critical goals."},
                },
                {
                    "id": "D01-Q07",
                    "prompt": {"id": "Catatan tambahan tentang visi atau business case (opsional)", "en": "Additional notes about vision or business case (optional)"},
                    "type": "text_long",
                    "help": {"id": "Apapun yang ingin Anda sampaikan tentang arah bisnis.", "en": "Anything about business direction."},
                },
            ],
        },
        {
            "id": "D02",
            "number": 2,
            "code": "current-state",
            "title": {"id": "Kondisi Sistem Existing & Pain Points", "en": "Existing System & Pain Points"},
            "icon": "AlertTriangle",
            "color": "amber",
            "recommended_pic": ["CEO / Owner", "IT Manager", "Operations Head"],
            "estimated_minutes": 20,
            "description": {"id": "Memahami sistem yang sedang dipakai dan masalah-masalah utama.", "en": "Understanding current systems and main pain points."},
            "questions": [
                {
                    "id": "D02-Q01",
                    "prompt": {"id": "Bagaimana sistem pencatatan transaksi saat ini?", "en": "Current transaction recording system?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "manual_paper", "label": "Manual / Buku tulis / Form kertas"},
                        {"value": "excel_only", "label": "Excel / Google Sheet"},
                        {"value": "accounting_software", "label": "Software accounting (Accurate / Zahir / Jurnal)"},
                        {"value": "custom_app", "label": "Aplikasi custom in-house"},
                        {"value": "erp_lama", "label": "Sudah pakai ERP tapi mau ganti"},
                        {"value": "mixed", "label": "Campuran beberapa sistem di atas"},
                    ],
                    "help": {"id": "Penting untuk strategi migrasi data.", "en": "Important for data migration strategy."},
                },
                {
                    "id": "D02-Q02",
                    "prompt": {"id": "Software / tools apa saja yang sedang digunakan? (pilih semua yang relevan)", "en": "Current software/tools in use?"},
                    "type": "multi_choice",
                    "options": [
                        {"value": "accurate", "label": "Accurate"},
                        {"value": "zahir", "label": "Zahir"},
                        {"value": "jurnal", "label": "Jurnal (Mekari)"},
                        {"value": "moka_pos", "label": "Moka POS"},
                        {"value": "excel", "label": "Microsoft Excel / Google Sheets"},
                        {"value": "tokopedia", "label": "Marketplace: Tokopedia"},
                        {"value": "shopee", "label": "Marketplace: Shopee"},
                        {"value": "tiktok_shop", "label": "Marketplace: TikTok Shop"},
                        {"value": "whatsapp_business", "label": "WhatsApp Business untuk order"},
                        {"value": "custom", "label": "Aplikasi custom buatan internal"},
                        {"value": "none", "label": "Tidak ada / Manual saja"},
                    ],
                    "help": {"id": "Daftar lengkap tools yang aktif.", "en": "List of all active tools."},
                },
                {
                    "id": "D02-Q03",
                    "prompt": {"id": "Seberapa parah pain point 'selisih stok' di gudang saat ini?", "en": "How severe is the inventory discrepancy problem?"},
                    "type": "scale_1_5",
                    "scale_labels": {"1": "Tidak ada masalah", "3": "Sedang", "5": "Sangat parah, sering rugi"},
                    "help": {"id": "Selisih stok = perbedaan antara catatan sistem vs fisik di gudang.", "en": "Inventory discrepancy = difference between system records and physical stock."},
                },
                {
                    "id": "D02-Q04",
                    "prompt": {"id": "Seberapa parah pain point 'laporan terlambat / tidak akurat'?", "en": "How severe is the late/inaccurate reporting problem?"},
                    "type": "scale_1_5",
                    "scale_labels": {"1": "Laporan real-time", "3": "Mingguan", "5": "Bulanan / sering salah"},
                    "help": {"id": "Seberapa sering Anda mendapat laporan operasional yang up-to-date?", "en": "How often do you get up-to-date operational reports?"},
                },
                {
                    "id": "D02-Q05",
                    "prompt": {"id": "Seberapa parah pain point 'human error pada data entry'?", "en": "How severe is the data entry human error problem?"},
                    "type": "scale_1_5",
                    "scale_labels": {"1": "Hampir tidak ada", "3": "Cukup sering", "5": "Setiap hari"},
                    "help": {"id": "Misal: salah input qty, salah pilih customer, salah harga.", "en": "E.g.: wrong quantity input, wrong customer selection, wrong price."},
                },
                {
                    "id": "D02-Q06",
                    "prompt": {"id": "Estimasi kerugian finansial per bulan akibat masalah sistem saat ini (Rp)?", "en": "Estimated monthly financial loss due to current system issues?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "under_10jt", "label": "Di bawah Rp 10 juta"},
                        {"value": "10_50jt", "label": "Rp 10 – 50 juta"},
                        {"value": "50_100jt", "label": "Rp 50 – 100 juta"},
                        {"value": "100_500jt", "label": "Rp 100 – 500 juta"},
                        {"value": "500jt_plus", "label": "Di atas Rp 500 juta"},
                        {"value": "unknown", "label": "Belum pernah dihitung"},
                    ],
                    "help": {"id": "Estimasi total kerugian: selisih stok, dead stock, labor inefisiensi.", "en": "Total loss estimate: inventory discrepancy, dead stock, labor inefficiency."},
                },
                {
                    "id": "D02-Q07",
                    "prompt": {"id": "Tiga pain points teratas yang PALING ingin diselesaikan", "en": "Top 3 pain points to solve"},
                    "type": "text_long",
                    "help": {"id": "Tulis 3 hal yang paling mengganggu operasional saat ini.", "en": "Write the 3 most disruptive operational problems."},
                },
            ],
        },
        {
            "id": "D03",
            "number": 3,
            "code": "procurement",
            "title": {"id": "Proses Pembelian (Purchase to Pay)", "en": "Procurement (Purchase to Pay)"},
            "icon": "ShoppingCart",
            "color": "purple",
            "recommended_pic": ["Procurement Manager", "Finance Manager"],
            "estimated_minutes": 15,
            "description": {"id": "Memahami alur pembelian dari permintaan barang sampai pembayaran ke supplier.", "en": "Understanding the procurement flow from requisition to supplier payment."},
            "questions": [
                {
                    "id": "D03-Q01",
                    "prompt": {"id": "Berapa rata-rata jumlah Purchase Order (PO) per bulan?", "en": "Average number of Purchase Orders per month?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "under_10", "label": "Di bawah 10 PO/bulan"},
                        {"value": "10_50", "label": "10 – 50 PO/bulan"},
                        {"value": "50_200", "label": "50 – 200 PO/bulan"},
                        {"value": "200_500", "label": "200 – 500 PO/bulan"},
                        {"value": "500_plus", "label": "Lebih dari 500 PO/bulan"},
                    ],
                    "help": {"id": "PO = Purchase Order = surat pesanan resmi ke supplier.", "en": "PO = Purchase Order = formal order to supplier."},
                },
                {
                    "id": "D03-Q02",
                    "prompt": {"id": "Berapa jumlah supplier aktif?", "en": "Number of active suppliers?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "under_20", "label": "Kurang dari 20 supplier"},
                        {"value": "20_50", "label": "20 – 50 supplier"},
                        {"value": "50_200", "label": "50 – 200 supplier"},
                        {"value": "200_plus", "label": "Lebih dari 200 supplier"},
                    ],
                    "help": {"id": "Supplier yang masih aktif kirim barang ke Anda.", "en": "Suppliers still actively delivering to you."},
                },
                {
                    "id": "D03-Q03",
                    "prompt": {"id": "Bagaimana proses approval PO saat ini?", "en": "Current PO approval process?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "no_approval", "label": "Tidak ada approval"},
                        {"value": "single_approval", "label": "1 level approval (Manager / Direktur)"},
                        {"value": "tiered", "label": "Berjenjang berdasarkan nominal"},
                        {"value": "matrix", "label": "Matrix approval (per kategori + nominal)"},
                    ],
                    "help": {"id": "Approval = persetujuan sebelum PO dikirim ke supplier.", "en": "Approval = sign-off before PO is sent to supplier."},
                },
                {
                    "id": "D03-Q04",
                    "prompt": {"id": "Term pembayaran ke supplier yang paling umum?", "en": "Most common payment terms to suppliers?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "cod", "label": "COD (bayar saat barang datang)"},
                        {"value": "net_7", "label": "Net 7 hari"},
                        {"value": "net_30", "label": "Net 30 hari"},
                        {"value": "net_60", "label": "Net 60 hari"},
                        {"value": "net_90", "label": "Net 90 hari"},
                        {"value": "mixed", "label": "Bervariasi tergantung supplier"},
                    ],
                    "help": {"id": "Ini perlu di-track sistem untuk cash flow forecasting.", "en": "This needs to be tracked for cash flow forecasting."},
                },
                {
                    "id": "D03-Q05",
                    "prompt": {"id": "Apakah ada supplier yang KRITIKAL (>30% supply dari 1 supplier)?", "en": "Any CRITICAL supplier (>30% of supply from 1 supplier)?"},
                    "type": "yes_no",
                    "help": {"id": "Supplier kritikal = kalau stop kirim, operasional terganggu serius.", "en": "Critical supplier = if they stop, operations are severely disrupted."},
                },
                {
                    "id": "D03-Q06",
                    "prompt": {"id": "Catatan khusus tentang proses pembelian (opsional)", "en": "Special notes about procurement (optional)"},
                    "type": "text_long",
                    "help": {"id": "Misal: ada supplier yang harus pakai sistem khusus.", "en": "E.g.: suppliers requiring special systems."},
                },
            ],
        },
        {
            "id": "D04",
            "number": 4,
            "code": "warehouse-inventory",
            "title": {"id": "Gudang & Manajemen Stok", "en": "Warehouse & Inventory Management"},
            "icon": "Warehouse",
            "color": "emerald",
            "recommended_pic": ["Warehouse Manager", "Operations Head", "Inventory Controller"],
            "estimated_minutes": 30,
            "description": {"id": "Bagian PALING KRITIKAL — ini jantung dari ERP Anda.", "en": "MOST CRITICAL section — the heart of your ERP."},
            "questions": [
                {
                    "id": "D04-Q01",
                    "prompt": {"id": "Berapa jumlah SKU (variant produk) yang aktif saat ini?", "en": "Number of active SKUs?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "under_100", "label": "Kurang dari 100 SKU"},
                        {"value": "100_500", "label": "100 – 500 SKU"},
                        {"value": "500_2000", "label": "500 – 2.000 SKU"},
                        {"value": "2000_10000", "label": "2.000 – 10.000 SKU"},
                        {"value": "10000_plus", "label": "Lebih dari 10.000 SKU"},
                    ],
                    "help": {"id": "SKU = setiap variant unik produk.", "en": "SKU = each unique product variant."},
                },
                {
                    "id": "D04-Q02",
                    "prompt": {"id": "Bagaimana sistem identifikasi item di gudang saat ini?", "en": "Current item identification system in warehouse?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "no_label", "label": "Tidak ada label, andalkan ingatan staff"},
                        {"value": "manual_label", "label": "Label kertas tulis tangan"},
                        {"value": "barcode_print", "label": "Barcode (dicetak) + scanner"},
                        {"value": "rfid", "label": "Sudah pakai RFID"},
                        {"value": "mixed", "label": "Campuran beberapa metode"},
                    ],
                    "help": {"id": "Identifikasi = cara membedakan item satu dengan lain di gudang.", "en": "Identification = how to differentiate items in the warehouse."},
                },
                {
                    "id": "D04-Q03",
                    "prompt": {"id": "Apakah ada konsep BATCH / LOT / ROLL untuk produk?", "en": "Any BATCH / LOT / ROLL concept for products?"},
                    "type": "multi_choice",
                    "options": [
                        {"value": "batch", "label": "Batch (kelompok produksi)"},
                        {"value": "lot", "label": "Lot (sub-batch)"},
                        {"value": "roll", "label": "Roll (gulungan kain individual)"},
                        {"value": "color_dyelot", "label": "Color Dyelot (batch pewarnaan)"},
                        {"value": "none", "label": "Tidak ada — produk fungible"},
                    ],
                    "help": {"id": "Kain umumnya punya variasi warna per gulungan (dyelot).", "en": "Fabric typically has color variation per roll (dyelot)."},
                },
                {
                    "id": "D04-Q04",
                    "prompt": {"id": "Satuan ukur (Unit of Measure) yang dipakai?", "en": "Units of Measure in use?"},
                    "type": "multi_choice",
                    "options": [
                        {"value": "meter", "label": "Meter"},
                        {"value": "yard", "label": "Yard"},
                        {"value": "roll", "label": "Roll / Gulungan"},
                        {"value": "kg", "label": "Kilogram"},
                        {"value": "pcs", "label": "Pcs (untuk produk jadi)"},
                        {"value": "lembar", "label": "Lembar"},
                    ],
                    "help": {"id": "Sistem harus support konversi otomatis.", "en": "System needs to support automatic conversion."},
                },
                {
                    "id": "D04-Q05",
                    "prompt": {"id": "Metode penilaian stok (inventory valuation) saat ini?", "en": "Current inventory valuation method?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "fifo", "label": "FIFO (First In First Out)"},
                        {"value": "lifo", "label": "LIFO (Last In First Out)"},
                        {"value": "weighted_avg", "label": "Weighted Average Cost"},
                        {"value": "specific_id", "label": "Specific Identification (per roll/batch)"},
                        {"value": "unknown", "label": "Belum ditetapkan formal"},
                    ],
                    "help": {"id": "Cara menghitung HPP (Harga Pokok Penjualan).", "en": "How to calculate COGS."},
                },
                {
                    "id": "D04-Q06",
                    "prompt": {"id": "Seberapa sering stok opname dilakukan?", "en": "How often is physical inventory count conducted?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "daily", "label": "Setiap hari (cycle count selective)"},
                        {"value": "weekly", "label": "Mingguan"},
                        {"value": "monthly", "label": "Bulanan"},
                        {"value": "quarterly", "label": "Per 3 bulan"},
                        {"value": "yearly", "label": "Tahunan saja"},
                        {"value": "ad_hoc", "label": "Tidak terjadwal"},
                    ],
                    "help": {"id": "Frekuensi opname menentukan tingkat akurasi sistem.", "en": "Frequency determines system accuracy level."},
                },
                {
                    "id": "D04-Q07",
                    "prompt": {"id": "Berapa lama waktu 1x stok opname menyeluruh saat ini?", "en": "How long does one full stock count take?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "under_1day", "label": "Kurang dari 1 hari"},
                        {"value": "1_3day", "label": "1 – 3 hari"},
                        {"value": "3_7day", "label": "3 – 7 hari (stop operasi)"},
                        {"value": "1_4weeks", "label": "1 – 4 minggu"},
                        {"value": "rarely_done", "label": "Jarang dilakukan menyeluruh"},
                    ],
                    "help": {"id": "RFID bisa mengurangi waktu opname 10x lipat.", "en": "RFID can reduce stock count time by 10x."},
                },
                {
                    "id": "D04-Q08",
                    "prompt": {"id": "Apakah sudah ada konsep ZONE / RACK / BIN di gudang?", "en": "Any ZONE / RACK / BIN concept in warehouse?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "fully_organized", "label": "Sudah lengkap (Zone, Rack, Bin terlabeli)"},
                        {"value": "zone_only", "label": "Hanya Zone (area besar)"},
                        {"value": "informal", "label": "Ada pembagian tapi tidak formal"},
                        {"value": "none", "label": "Belum ada — penempatan ad-hoc"},
                    ],
                    "help": {"id": "Penting untuk picking efisien & lokasi traceable.", "en": "Important for efficient picking and traceable location."},
                },
                {
                    "id": "D04-Q09",
                    "prompt": {"id": "Apakah butuh fitur RESERVATION stok?", "en": "Need STOCK RESERVATION feature?"},
                    "type": "yes_no",
                    "help": {"id": "Misal: stok di-LOCK untuk customer tertentu sebelum dikirim.", "en": "E.g.: stock LOCKed for a specific customer before shipment."},
                },
                {
                    "id": "D04-Q10",
                    "prompt": {"id": "Catatan khusus tentang operasional gudang (opsional)", "en": "Special notes about warehouse operations (optional)"},
                    "type": "text_long",
                    "help": {"id": "Misal: kain harus disimpan dengan kelembaban tertentu.", "en": "E.g.: fabric requires specific humidity storage."},
                },
            ],
        },
        {
            "id": "D05",
            "number": 5,
            "code": "sales-distribution",
            "title": {"id": "Penjualan & Distribusi (Order to Cash)", "en": "Sales & Distribution (Order to Cash)"},
            "icon": "TrendingUp",
            "color": "rose",
            "recommended_pic": ["Sales Manager", "Operations Head"],
            "estimated_minutes": 20,
            "description": {"id": "Memahami alur penjualan dari quotation sampai pembayaran masuk.", "en": "Understanding the sales flow from quotation to payment."},
            "questions": [
                {
                    "id": "D05-Q01",
                    "prompt": {"id": "Channel penjualan yang aktif saat ini? (pilih semua)", "en": "Active sales channels? (select all)"},
                    "type": "multi_choice",
                    "options": [
                        {"value": "offline_b2b", "label": "Offline B2B (canvasing, kantor, sales lapangan)"},
                        {"value": "offline_b2c", "label": "Offline B2C (toko sendiri)"},
                        {"value": "online_marketplace", "label": "Marketplace (Tokopedia, Shopee, dll)"},
                        {"value": "online_website", "label": "Website e-commerce sendiri"},
                        {"value": "social_commerce", "label": "Social Commerce (IG, WA, FB)"},
                        {"value": "distributor", "label": "Via distributor / mitra reseller"},
                        {"value": "export", "label": "Export (luar negeri)"},
                    ],
                    "help": {"id": "Setiap channel butuh konfigurasi berbeda.", "en": "Each channel needs different configuration."},
                },
                {
                    "id": "D05-Q02",
                    "prompt": {"id": "Berapa rata-rata Sales Order (SO) per bulan?", "en": "Average Sales Orders per month?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "under_100", "label": "Kurang dari 100 SO/bulan"},
                        {"value": "100_500", "label": "100 – 500 SO/bulan"},
                        {"value": "500_2000", "label": "500 – 2.000 SO/bulan"},
                        {"value": "2000_10000", "label": "2.000 – 10.000 SO/bulan"},
                        {"value": "10000_plus", "label": "Lebih dari 10.000 SO/bulan"},
                    ],
                    "help": {"id": "SO = Sales Order = pesanan yang masuk dari customer.", "en": "SO = Sales Order = orders received from customers."},
                },
                {
                    "id": "D05-Q03",
                    "prompt": {"id": "Berapa jumlah customer aktif (6 bulan terakhir)?", "en": "Number of active customers (last 6 months)?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "under_50", "label": "Kurang dari 50"},
                        {"value": "50_200", "label": "50 – 200"},
                        {"value": "200_1000", "label": "200 – 1.000"},
                        {"value": "1000_5000", "label": "1.000 – 5.000"},
                        {"value": "5000_plus", "label": "Lebih dari 5.000"},
                    ],
                    "help": {"id": "Customer aktif = yang masih transaksi.", "en": "Active customers = those still transacting."},
                },
                {
                    "id": "D05-Q04",
                    "prompt": {"id": "Apakah ada konsep TIERED PRICING (harga berbeda per segmen customer)?", "en": "Any TIERED PRICING concept?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "uniform", "label": "Tidak — semua customer harga sama"},
                        {"value": "tier_2_3", "label": "Ya — 2-3 tier (Retail / Wholesale)"},
                        {"value": "tier_4plus", "label": "Ya — 4+ tier"},
                        {"value": "contract", "label": "Ya — per kontrak individual"},
                        {"value": "complex", "label": "Kompleks (kombinasi tier + kontrak + promo)"},
                    ],
                    "help": {"id": "Tiered Pricing = harga berbeda untuk grup customer berbeda.", "en": "Tiered Pricing = different prices for different customer groups."},
                },
                {
                    "id": "D05-Q05",
                    "prompt": {"id": "Term pembayaran dari customer yang paling umum?", "en": "Most common payment terms from customers?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "cash_upfront", "label": "Cash di muka"},
                        {"value": "cod", "label": "COD"},
                        {"value": "net_7", "label": "Net 7 hari"},
                        {"value": "net_30", "label": "Net 30 hari"},
                        {"value": "net_60", "label": "Net 60 hari"},
                        {"value": "mixed", "label": "Campuran"},
                    ],
                    "help": {"id": "Term pembayaran customer mempengaruhi cash flow.", "en": "Customer payment terms affect cash flow."},
                },
                {
                    "id": "D05-Q06",
                    "prompt": {"id": "Metode pengiriman barang?", "en": "Delivery methods?"},
                    "type": "multi_choice",
                    "options": [
                        {"value": "own_fleet", "label": "Armada sendiri"},
                        {"value": "rented_fleet", "label": "Armada sewa"},
                        {"value": "expedition_jne", "label": "JNE / J&T / SiCepat / dll"},
                        {"value": "3pl", "label": "3PL / freight forwarder"},
                        {"value": "customer_pickup", "label": "Customer ambil sendiri"},
                    ],
                    "help": {"id": "Method pengiriman mempengaruhi integrasi shipping API.", "en": "Delivery method affects shipping API integration."},
                },
                {
                    "id": "D05-Q07",
                    "prompt": {"id": "Apakah ada Sales Force lapangan yang butuh aplikasi mobile?", "en": "Any field sales force needing mobile app?"},
                    "type": "yes_no",
                    "help": {"id": "Sales Force lapangan butuh fitur mobile dengan offline mode.", "en": "Field sales needs mobile with offline mode."},
                },
                {
                    "id": "D05-Q08",
                    "prompt": {"id": "Catatan khusus tentang proses penjualan (opsional)", "en": "Special notes about sales process (optional)"},
                    "type": "text_long",
                    "help": {"id": "Misal: customer tertentu butuh format invoice khusus.", "en": "E.g.: certain customers need special invoice format."},
                },
            ],
        },
        {
            "id": "D06",
            "number": 6,
            "code": "finance-accounting",
            "title": {"id": "Finance & Akunting", "en": "Finance & Accounting"},
            "icon": "Wallet",
            "color": "indigo",
            "recommended_pic": ["CFO / Finance Manager", "Chief Accountant"],
            "estimated_minutes": 20,
            "description": {"id": "Memahami kebutuhan akuntansi, perpajakan, dan pelaporan keuangan.", "en": "Understanding accounting, taxation, and financial reporting needs."},
            "questions": [
                {
                    "id": "D06-Q01",
                    "prompt": {"id": "Apakah sudah punya Chart of Accounts (COA) formal?", "en": "Have a formal Chart of Accounts?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "yes_psak", "label": "Ya — sesuai PSAK / SAK ETAP"},
                        {"value": "yes_custom", "label": "Ya — custom (buatan internal)"},
                        {"value": "partial", "label": "Sebagian saja (belum lengkap)"},
                        {"value": "no", "label": "Belum ada"},
                    ],
                    "help": {"id": "COA = daftar akun untuk pembukuan. PSAK = standar akuntansi Indonesia.", "en": "COA = chart of accounts. PSAK = Indonesian accounting standard."},
                },
                {
                    "id": "D06-Q02",
                    "prompt": {"id": "Status PKP — apakah wajib PPN?", "en": "VAT taxpayer status?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "pkp", "label": "Ya — PKP (wajib pungut PPN 11%)"},
                        {"value": "non_pkp", "label": "Tidak — Non-PKP"},
                        {"value": "planning_pkp", "label": "Sedang proses pengajuan PKP"},
                        {"value": "unknown", "label": "Belum tahu pasti"},
                    ],
                    "help": {"id": "PKP wajib menerbitkan Faktur Pajak untuk setiap penjualan.", "en": "VAT taxpayers must issue tax invoices for each sale."},
                },
                {
                    "id": "D06-Q03",
                    "prompt": {"id": "Pajak apa saja yang relevan? (pilih semua)", "en": "Relevant taxes? (select all)"},
                    "type": "multi_choice",
                    "show_if": {"question_id": "D06-Q02", "operator": "not_equals", "value": "non_pkp"},
                    "options": [
                        {"value": "pph21", "label": "PPh 21 (gaji karyawan)"},
                        {"value": "pph23", "label": "PPh 23 (jasa)"},
                        {"value": "pph_final", "label": "PPh Final UMKM"},
                        {"value": "ppn", "label": "PPN 11%"},
                        {"value": "pph_22", "label": "PPh 22 (import)"},
                        {"value": "pph_4_ayat_2", "label": "PPh 4(2) (sewa, jasa konstruksi)"},
                    ],
                    "help": {"id": "Sistem akan menghitung & memotong pajak otomatis.", "en": "System will calculate and withhold taxes automatically."},
                },
                {
                    "id": "D06-Q04",
                    "prompt": {"id": "Berapa banyak rekening bank yang aktif?", "en": "Number of active bank accounts?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "1", "label": "1 rekening"},
                        {"value": "2_3", "label": "2 – 3 rekening"},
                        {"value": "4_10", "label": "4 – 10 rekening"},
                        {"value": "10_plus", "label": "Lebih dari 10 rekening"},
                    ],
                    "help": {"id": "Sistem perlu support multi-bank untuk rekonsiliasi otomatis.", "en": "System needs multi-bank support for auto-reconciliation."},
                },
                {
                    "id": "D06-Q05",
                    "prompt": {"id": "Apakah butuh fitur AUTO BANK RECONCILIATION?", "en": "Need AUTO BANK RECONCILIATION feature?"},
                    "type": "single_choice",
                    "show_if": {"question_id": "D06-Q04", "operator": "not_in", "values": ["1"]},
                    "options": [
                        {"value": "critical", "label": "Sangat butuh — saat ini sangat memakan waktu"},
                        {"value": "nice", "label": "Akan sangat membantu"},
                        {"value": "not_urgent", "label": "Belum urgent — manual masih OK"},
                        {"value": "no_need", "label": "Tidak butuh"},
                    ],
                    "help": {"id": "Auto rekonsiliasi = sistem otomatis cocokkan mutasi bank dengan invoice.", "en": "Auto reconciliation = system automatically matches bank transactions with invoices."},
                },
                {
                    "id": "D06-Q06",
                    "prompt": {"id": "Berapa lama waktu yang dibutuhkan untuk closing bulanan saat ini?", "en": "How long does monthly closing take?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "under_5day", "label": "Kurang dari 5 hari kerja"},
                        {"value": "5_10day", "label": "5 – 10 hari kerja"},
                        {"value": "10_20day", "label": "10 – 20 hari kerja"},
                        {"value": "20_plus", "label": "Lebih dari 20 hari kerja"},
                        {"value": "no_closing", "label": "Tidak ada closing rutin"},
                    ],
                    "help": {"id": "Target ERP: closing < 5 hari.", "en": "ERP target: closing < 5 days."},
                },
                {
                    "id": "D06-Q07",
                    "prompt": {"id": "Apakah ada rencana audit eksternal / IPO dalam 2-3 tahun?", "en": "Any external audit / IPO plans in 2-3 years?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "ipo", "label": "Ada rencana IPO"},
                        {"value": "external_audit", "label": "Audit eksternal rutin"},
                        {"value": "considering", "label": "Sedang dipertimbangkan"},
                        {"value": "no", "label": "Belum ada rencana"},
                    ],
                    "help": {"id": "Audit/IPO butuh audit trail lengkap & laporan formal.", "en": "Audit/IPO requires complete audit trail and formal reports."},
                },
            ],
        },
        {
            "id": "D07",
            "number": 7,
            "code": "rfid-assessment",
            "title": {"id": "RFID & Identifikasi Otomatis", "en": "RFID & Automatic Identification"},
            "icon": "Radio",
            "color": "violet",
            "recommended_pic": ["Operations Manager", "IT Manager", "Warehouse Manager"],
            "estimated_minutes": 15,
            "description": {"id": "Assessment kebutuhan RFID untuk meningkatkan akurasi stok.", "en": "RFID needs assessment for improved stock accuracy."},
            "questions": [
                {
                    "id": "D07-Q01",
                    "prompt": {"id": "Seberapa familiar tim Anda dengan teknologi RFID?", "en": "How familiar is your team with RFID technology?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "expert", "label": "Sangat familiar — sudah pernah implementasi"},
                        {"value": "moderate", "label": "Cukup paham konsep dasar"},
                        {"value": "basic", "label": "Sedikit tahu, butuh edukasi"},
                        {"value": "none", "label": "Belum tahu sama sekali"},
                    ],
                    "help": {"id": "RFID = tag wireless di setiap item, dibaca otomatis tanpa harus dilihat langsung.", "en": "RFID = wireless tag on each item, read automatically without direct line-of-sight."},
                },
                {
                    "id": "D07-Q02",
                    "prompt": {"id": "Tujuan utama implementasi RFID? (pilih maks 2)", "en": "Main RFID implementation goals? (max 2)"},
                    "type": "multi_choice",
                    "max_select": 2,
                    "options": [
                        {"value": "stock_accuracy", "label": "Akurasi stok > 99%"},
                        {"value": "faster_opname", "label": "Mempercepat stok opname (10x lipat)"},
                        {"value": "reduce_shrinkage", "label": "Mengurangi kehilangan/pencurian"},
                        {"value": "auto_receiving", "label": "Otomatisasi receiving di pintu gudang"},
                        {"value": "auto_shipping", "label": "Otomatisasi verifikasi shipping"},
                        {"value": "anti_counterfeit", "label": "Anti-pemalsuan produk premium"},
                        {"value": "exploratory", "label": "Masih eksplorasi — belum tahu pasti"},
                    ],
                    "help": {"id": "RFID adalah investasi besar (~Rp 500jt-1M), pastikan ROI-nya jelas.", "en": "RFID is a major investment, ensure clear ROI."},
                },
                {
                    "id": "D07-Q03",
                    "prompt": {"id": "Berapa nilai rata-rata per item produk Anda?", "en": "Average value per product item?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "under_50k", "label": "Di bawah Rp 50 ribu/item"},
                        {"value": "50_500k", "label": "Rp 50 ribu – Rp 500 ribu/item"},
                        {"value": "500k_2jt", "label": "Rp 500 ribu – Rp 2 juta/item"},
                        {"value": "2jt_plus", "label": "Di atas Rp 2 juta/item"},
                    ],
                    "help": {"id": "RFID tag harganya ~Rp 500-3000/tag. Untuk produk < Rp 50rb, RFID per-item tidak feasible.", "en": "RFID tag costs ~Rp 500-3000/tag. Not feasible per-item for products < Rp 50k."},
                },
                {
                    "id": "D07-Q04",
                    "prompt": {"id": "Tipe RFID yang akan dipakai?", "en": "RFID type preference?"},
                    "type": "single_choice",
                    "show_if": {"question_id": "D07-Q02", "operator": "not_includes", "values": ["exploratory"]},
                    "options": [
                        {"value": "uhf", "label": "UHF (passive, jangkauan 5-10m) — paling umum untuk warehouse"},
                        {"value": "hf_nfc", "label": "HF / NFC (jangkauan dekat, untuk anti-counterfeit retail)"},
                        {"value": "active", "label": "Active RFID (battery-powered, untuk aset besar)"},
                        {"value": "tbd", "label": "Belum ditentukan"},
                    ],
                    "help": {"id": "UHF = paling cocok untuk gudang tekstil/distribusi.", "en": "UHF = best for textile/distribution warehouse."},
                },
                {
                    "id": "D07-Q05",
                    "prompt": {"id": "Berapa banyak pintu gudang yang perlu dipasang RFID Gate?", "en": "How many warehouse doors need RFID Gate?"},
                    "type": "single_choice",
                    "show_if": {"question_id": "D07-Q02", "operator": "not_includes", "values": ["exploratory"]},
                    "options": [
                        {"value": "0", "label": "0 (handheld scanner saja)"},
                        {"value": "1_2", "label": "1 – 2 pintu"},
                        {"value": "3_5", "label": "3 – 5 pintu"},
                        {"value": "5_plus", "label": "Lebih dari 5 pintu"},
                    ],
                    "help": {"id": "Per gate ~Rp 80-150jt setup.", "en": "Per gate ~Rp 80-150M setup cost."},
                },
                {
                    "id": "D07-Q06",
                    "prompt": {"id": "Apakah setuju untuk PROOF OF CONCEPT (POC) RFID dulu sebelum full rollout?", "en": "Agree to RFID Proof of Concept before full rollout?"},
                    "type": "yes_no",
                    "help": {"id": "POC = uji coba skala kecil (3-4 minggu). SANGAT DIREKOMENDASIKAN.", "en": "POC = small-scale test (3-4 weeks). HIGHLY RECOMMENDED."},
                },
            ],
        },
        {
            "id": "D08",
            "number": 8,
            "code": "system-integration",
            "title": {"id": "Integrasi Sistem (E-commerce, Banking, dll)", "en": "System Integration (E-commerce, Banking, etc.)"},
            "icon": "Network",
            "color": "cyan",
            "recommended_pic": ["IT Manager", "E-commerce Manager"],
            "estimated_minutes": 12,
            "description": {"id": "Sistem ERP tidak berdiri sendiri. Identifikasi sistem lain yang perlu terhubung.", "en": "ERP doesn't stand alone. Identify other systems that need integration."},
            "questions": [
                {
                    "id": "D08-Q01",
                    "prompt": {"id": "Marketplace / e-commerce yang perlu terintegrasi otomatis? (pilih semua)", "en": "Marketplace/e-commerce for automatic integration?"},
                    "type": "multi_choice",
                    "options": [
                        {"value": "tokopedia", "label": "Tokopedia"},
                        {"value": "shopee", "label": "Shopee"},
                        {"value": "tiktok_shop", "label": "TikTok Shop"},
                        {"value": "lazada", "label": "Lazada"},
                        {"value": "bukalapak", "label": "Bukalapak"},
                        {"value": "own_website", "label": "Website e-commerce sendiri"},
                        {"value": "shopify", "label": "Shopify"},
                        {"value": "none", "label": "Tidak ada / belum perlu"},
                    ],
                    "help": {"id": "Integrasi = order dari marketplace otomatis masuk ERP.", "en": "Integration = marketplace orders automatically enter ERP."},
                },
                {
                    "id": "D08-Q02",
                    "prompt": {"id": "Software accounting yang harus tetap dipakai (legacy)?", "en": "Legacy accounting software to keep?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "accurate", "label": "Accurate"},
                        {"value": "zahir", "label": "Zahir"},
                        {"value": "jurnal", "label": "Jurnal (Mekari)"},
                        {"value": "sap", "label": "SAP"},
                        {"value": "custom", "label": "Custom in-house"},
                        {"value": "none_replace_all", "label": "Tidak ada — ERP baru akan ganti semua"},
                    ],
                    "help": {"id": "Kalau ada legacy accounting yang harus tetap dipakai, ERP perlu sync data.", "en": "If legacy accounting must remain, ERP needs data sync."},
                },
                {
                    "id": "D08-Q03",
                    "prompt": {"id": "Bank yang dipakai (untuk integrasi mutasi rekening)?", "en": "Banks used (for transaction mutation integration)?"},
                    "type": "multi_choice",
                    "options": [
                        {"value": "bca", "label": "BCA"},
                        {"value": "mandiri", "label": "Mandiri"},
                        {"value": "bni", "label": "BNI"},
                        {"value": "bri", "label": "BRI"},
                        {"value": "cimb", "label": "CIMB Niaga"},
                        {"value": "other", "label": "Bank lain"},
                    ],
                    "help": {"id": "Integrasi bank untuk auto-fetch mutasi → rekonsiliasi otomatis.", "en": "Bank integration for auto-fetch mutations → automatic reconciliation."},
                },
                {
                    "id": "D08-Q04",
                    "prompt": {"id": "Apakah perlu integrasi pajak (e-Faktur DJP)?", "en": "Need tax system integration (e-Faktur DJP)?"},
                    "type": "yes_no",
                    "show_if": {"question_id": "D06-Q02", "operator": "not_equals", "value": "non_pkp"},
                    "help": {"id": "e-Faktur = sistem pajak elektronik dari DJP. Wajib untuk PKP.", "en": "e-Faktur = electronic tax system from DGT. Mandatory for VAT taxpayers."},
                },
                {
                    "id": "D08-Q05",
                    "prompt": {"id": "Sistem lain yang perlu terhubung (opsional)", "en": "Other systems to connect (optional)"},
                    "type": "text_long",
                    "help": {"id": "Sebutkan sistem lain seperti HRIS, CRM, BI tools, dll.", "en": "Mention other systems like HRIS, CRM, BI tools, etc."},
                },
            ],
        },
        {
            "id": "D09",
            "number": 9,
            "code": "data-migration",
            "title": {"id": "Master Data & Strategi Migrasi", "en": "Master Data & Migration Strategy"},
            "icon": "Database",
            "color": "teal",
            "recommended_pic": ["IT Manager", "Operations Head", "Finance Manager"],
            "estimated_minutes": 12,
            "description": {"id": "60-70% proyek ERP gagal karena data. Kondisi data existing sangat critical.", "en": "60-70% of ERP projects fail due to data issues. Existing data condition is critical."},
            "questions": [
                {
                    "id": "D09-Q01",
                    "prompt": {"id": "Dimana master data produk saat ini disimpan?", "en": "Where is product master data currently stored?"},
                    "type": "multi_choice",
                    "options": [
                        {"value": "excel", "label": "Excel / Google Sheets"},
                        {"value": "accounting_software", "label": "Software accounting"},
                        {"value": "buku_manual", "label": "Buku catatan manual"},
                        {"value": "marketplace", "label": "Tersebar di tiap marketplace"},
                        {"value": "no_master", "label": "Tidak ada master terpusat"},
                    ],
                    "help": {"id": "Master data produk = daftar lengkap SKU, harga, foto, deskripsi.", "en": "Product master data = complete SKU list, prices, photos, descriptions."},
                },
                {
                    "id": "D09-Q02",
                    "prompt": {"id": "Seberapa rapih data produk saat ini?", "en": "How clean is your product data?"},
                    "type": "scale_1_5",
                    "scale_labels": {"1": "Berantakan, banyak duplikasi", "3": "Cukup OK", "5": "Sangat rapih, terstandar"},
                    "help": {"id": "Skala 1 = banyak cleansing dibutuhkan sebelum migrasi.", "en": "Scale 1 = much cleansing needed before migration."},
                },
                {
                    "id": "D09-Q03",
                    "prompt": {"id": "Seberapa rapih data customer saat ini?", "en": "How clean is your customer data?"},
                    "type": "scale_1_5",
                    "scale_labels": {"1": "Berantakan, banyak duplikasi", "3": "Cukup OK", "5": "Sangat rapih, terstandar"},
                    "help": {"id": "Skala 1 = perlu deduplikasi besar sebelum migrasi.", "en": "Scale 1 = major deduplication needed before migration."},
                },
                {
                    "id": "D09-Q04",
                    "prompt": {"id": "Berapa periode historical data yang ingin dimigrasi?", "en": "How much historical data to migrate?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "no_history", "label": "Tidak ada — mulai dari nol di ERP baru"},
                        {"value": "3_months", "label": "3 bulan terakhir"},
                        {"value": "1_year", "label": "1 tahun terakhir"},
                        {"value": "3_years", "label": "3 tahun terakhir"},
                        {"value": "all_history", "label": "Semua riwayat"},
                    ],
                    "help": {"id": "Rekomendasi: 12 bulan untuk reporting & comparison.", "en": "Recommendation: 12 months for reporting and comparison."},
                },
                {
                    "id": "D09-Q05",
                    "prompt": {"id": "Siapa yang akan menjadi DATA STEWARD (penanggung jawab data)?", "en": "Who will be the DATA STEWARD?"},
                    "type": "text_long",
                    "help": {"id": "Data Steward = 1 orang per area yang bertanggung jawab data rapi sebelum migrasi.", "en": "Data Steward = 1 person per area responsible for clean data before migration."},
                },
            ],
        },
        {
            "id": "D10",
            "number": 10,
            "code": "infrastructure",
            "title": {"id": "Infrastruktur & Network", "en": "Infrastructure & Network"},
            "icon": "Server",
            "color": "slate",
            "recommended_pic": ["IT Manager", "Network Administrator"],
            "estimated_minutes": 10,
            "description": {"id": "Memastikan infrastruktur fisik siap mendukung ERP.", "en": "Ensuring physical infrastructure is ready to support ERP."},
            "questions": [
                {
                    "id": "D10-Q01",
                    "prompt": {"id": "Preferensi hosting ERP?", "en": "ERP hosting preference?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "cloud_saas", "label": "Cloud SaaS (data di server vendor)"},
                        {"value": "cloud_private", "label": "Cloud privat (AWS/Azure/GCP)"},
                        {"value": "on_premise", "label": "On-Premise (server di kantor kami)"},
                        {"value": "hybrid", "label": "Hybrid"},
                        {"value": "no_pref", "label": "Belum ada preferensi"},
                    ],
                    "help": {"id": "Cloud = fleksibel & scalable. On-prem = data kontrol penuh.", "en": "Cloud = flexible & scalable. On-prem = full data control."},
                },
                {
                    "id": "D10-Q02",
                    "prompt": {"id": "Kondisi internet di kantor pusat / gudang utama?", "en": "Internet condition at headquarters/main warehouse?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "fiber_stable", "label": "Fiber stabil (100+ Mbps, jarang putus)"},
                        {"value": "broadband", "label": "Broadband (10-100 Mbps, kadang lambat)"},
                        {"value": "limited", "label": "Terbatas (< 10 Mbps atau sering down)"},
                        {"value": "no_internet", "label": "Tidak ada internet stabil"},
                    ],
                    "help": {"id": "Bandwidth minimum ~10 Mbps per 20 user concurrent.", "en": "Minimum bandwidth ~10 Mbps per 20 concurrent users."},
                },
                {
                    "id": "D10-Q03",
                    "prompt": {"id": "Apakah ada WiFi coverage di area gudang (untuk handheld scanner)?", "en": "WiFi coverage in warehouse area (for handheld scanners)?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "full_coverage", "label": "Coverage penuh, sinyal kuat"},
                        {"value": "partial", "label": "Sebagian area saja"},
                        {"value": "weak", "label": "Ada tapi sinyal lemah"},
                        {"value": "no_wifi", "label": "Tidak ada WiFi di gudang"},
                    ],
                    "help": {"id": "RFID handheld & barcode scanner butuh WiFi stabil.", "en": "RFID handheld & barcode scanners need stable WiFi."},
                },
                {
                    "id": "D10-Q04",
                    "prompt": {"id": "Apakah ada strategi backup data formal saat ini?", "en": "Current formal data backup strategy?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "automated_offsite", "label": "Otomatis, offsite (cloud backup)"},
                        {"value": "automated_local", "label": "Otomatis tapi local"},
                        {"value": "manual", "label": "Manual, sesekali"},
                        {"value": "no_backup", "label": "Tidak ada backup formal"},
                    ],
                    "help": {"id": "Sistem ERP modern harus punya auto-backup harian + offsite copy.", "en": "Modern ERP must have daily auto-backup + offsite copy."},
                },
            ],
        },
        {
            "id": "D11",
            "number": 11,
            "code": "security-compliance",
            "title": {"id": "Keamanan & Compliance", "en": "Security & Compliance"},
            "icon": "ShieldCheck",
            "color": "red",
            "recommended_pic": ["IT Manager", "Compliance Officer", "CFO"],
            "estimated_minutes": 10,
            "description": {"id": "Aspek keamanan data dan kepatuhan terhadap regulasi.", "en": "Data security and regulatory compliance aspects."},
            "questions": [
                {
                    "id": "D11-Q01",
                    "prompt": {"id": "Apakah perusahaan punya kewajiban compliance khusus?", "en": "Any specific compliance obligations?"},
                    "type": "multi_choice",
                    "options": [
                        {"value": "iso_27001", "label": "ISO 27001 (Information Security)"},
                        {"value": "iso_9001", "label": "ISO 9001 (Quality Management)"},
                        {"value": "halal", "label": "Sertifikasi Halal"},
                        {"value": "ipo_ojk", "label": "Persiapan IPO (OJK requirements)"},
                        {"value": "uu_pdp", "label": "UU PDP 2022 (Perlindungan Data Pribadi)"},
                        {"value": "tax_audit", "label": "Audit pajak rutin (DJP)"},
                        {"value": "none_known", "label": "Belum ada / tidak yakin"},
                    ],
                    "help": {"id": "Compliance mempengaruhi level security & audit trail di sistem.", "en": "Compliance affects security level and audit trail in system."},
                },
                {
                    "id": "D11-Q02",
                    "prompt": {"id": "Berapa banyak peran (role) yang dibutuhkan di sistem?", "en": "How many roles needed in the system?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "under_5", "label": "Kurang dari 5 role"},
                        {"value": "5_10", "label": "5 – 10 role"},
                        {"value": "10_20", "label": "10 – 20 role"},
                        {"value": "20_plus", "label": "Lebih dari 20 role"},
                    ],
                    "help": {"id": "Role = posisi dengan permission berbeda. Lebih banyak = lebih kompleks RBAC.", "en": "Role = position with different permissions. More = more complex RBAC."},
                },
                {
                    "id": "D11-Q03",
                    "prompt": {"id": "Apakah butuh fitur Two-Factor Authentication (2FA)?", "en": "Need Two-Factor Authentication (2FA)?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "all_users", "label": "Ya, semua user wajib"},
                        {"value": "critical_only", "label": "Hanya untuk role critical (Admin, Finance)"},
                        {"value": "optional", "label": "Optional"},
                        {"value": "no", "label": "Belum perlu"},
                    ],
                    "help": {"id": "2FA = login butuh password + kode OTP dari HP.", "en": "2FA = login requires password + OTP code from phone."},
                },
                {
                    "id": "D11-Q04",
                    "prompt": {"id": "Apakah ada kebutuhan audit trail khusus?", "en": "Need special audit trail?"},
                    "type": "yes_no",
                    "help": {"id": "Audit trail = log semua perubahan data. Wajib untuk audit eksternal & IPO.", "en": "Audit trail = log all data changes. Mandatory for external audit & IPO."},
                },
            ],
        },
        {
            "id": "D12",
            "number": 12,
            "code": "change-management",
            "title": {"id": "Manajemen Perubahan & Pelatihan", "en": "Change Management & Training"},
            "icon": "Users",
            "color": "amber",
            "recommended_pic": ["HR Manager", "CEO", "Operations Head"],
            "estimated_minutes": 10,
            "description": {"id": "Sistem terbaik pun gagal kalau user tidak adopt.", "en": "Even the best system fails if users don't adopt it."},
            "questions": [
                {
                    "id": "D12-Q01",
                    "prompt": {"id": "Tingkat literasi teknologi rata-rata karyawan?", "en": "Average employee technology literacy level?"},
                    "type": "scale_1_5",
                    "scale_labels": {"1": "Sangat rendah (banyak yang anti tech)", "3": "Sedang (terbiasa Excel/HP)", "5": "Sangat tinggi (digital native)"},
                    "help": {"id": "Mempengaruhi durasi & metode training.", "en": "Affects training duration and method."},
                },
                {
                    "id": "D12-Q02",
                    "prompt": {"id": "Apakah pernah ada proyek IT besar sebelumnya?", "en": "Any previous large IT projects?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "successful", "label": "Pernah & sukses"},
                        {"value": "partial", "label": "Pernah & hasilnya sebagian sukses"},
                        {"value": "failed", "label": "Pernah & gagal / mengecewakan"},
                        {"value": "never", "label": "Belum pernah"},
                    ],
                    "help": {"id": "Pengalaman sebelumnya menentukan tingkat resistensi tim.", "en": "Previous experience determines team resistance level."},
                },
                {
                    "id": "D12-Q03",
                    "prompt": {"id": "Apakah siap menugaskan SUPER USER (3-10 orang internal yang dilatih intensif)?", "en": "Ready to assign SUPER USERS (3-10 intensively trained internal staff)?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "yes_committed", "label": "Ya, sudah ada kandidat & siap commit"},
                        {"value": "yes_will_assign", "label": "Ya, akan menugaskan saat proyek dimulai"},
                        {"value": "maybe", "label": "Pertimbangan, tergantung beban kerja"},
                        {"value": "no", "label": "Tidak"},
                    ],
                    "help": {"id": "Super User = expert internal yang jadi bridge antara user & vendor. KRITIKAL.", "en": "Super User = internal expert bridging users and vendor. CRITICAL."},
                },
                {
                    "id": "D12-Q04",
                    "prompt": {"id": "Preferensi metode training?", "en": "Training method preference?"},
                    "type": "multi_choice",
                    "options": [
                        {"value": "classroom", "label": "Classroom (tatap muka, di kantor)"},
                        {"value": "online_live", "label": "Online live (Zoom/Teams)"},
                        {"value": "video_self_paced", "label": "Video tutorial self-paced"},
                        {"value": "documentation", "label": "Dokumentasi tertulis (manual book)"},
                        {"value": "on_the_job", "label": "On the job training"},
                    ],
                    "help": {"id": "Pilih semua metode yang cocok.", "en": "Select all suitable methods."},
                },
            ],
        },
        {
            "id": "D13",
            "number": 13,
            "code": "vendor-budget",
            "title": {"id": "Vendor, Budget & Timeline", "en": "Vendor, Budget & Timeline"},
            "icon": "Banknote",
            "color": "green",
            "recommended_pic": ["CEO / Owner", "CFO"],
            "estimated_minutes": 10,
            "description": {"id": "Konteks komersial: budget, timeline, dan ekspektasi terhadap vendor.", "en": "Commercial context: budget, timeline, and vendor expectations."},
            "questions": [
                {
                    "id": "D13-Q01",
                    "prompt": {"id": "Range budget untuk implementasi ERP + RFID (5 tahun total)?", "en": "Budget range for ERP + RFID implementation (5-year total)?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "under_500jt", "label": "Di bawah Rp 500 juta"},
                        {"value": "500jt_2m", "label": "Rp 500 juta – Rp 2 Miliar"},
                        {"value": "2m_5m", "label": "Rp 2 – 5 Miliar"},
                        {"value": "5m_10m", "label": "Rp 5 – 10 Miliar"},
                        {"value": "10m_plus", "label": "Lebih dari Rp 10 Miliar"},
                        {"value": "no_budget_yet", "label": "Belum ditetapkan"},
                    ],
                    "help": {"id": "Range budget membantu vendor menyesuaikan scope.", "en": "Budget range helps vendor adjust scope."},
                },
                {
                    "id": "D13-Q02",
                    "prompt": {"id": "Timeline ekspektasi untuk go-live?", "en": "Expected go-live timeline?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "3_months", "label": "3 bulan (sangat agresif)"},
                        {"value": "6_months", "label": "6 bulan (agresif)"},
                        {"value": "9_12_months", "label": "9 – 12 bulan (standard)"},
                        {"value": "12_18_months", "label": "12 – 18 bulan (conservative)"},
                        {"value": "flexible", "label": "Fleksibel — yang penting hasil baik"},
                    ],
                    "help": {"id": "Timeline standard untuk ERP+RFID adalah 9-12 bulan.", "en": "Standard timeline for ERP+RFID is 9-12 months."},
                },
                {
                    "id": "D13-Q03",
                    "prompt": {"id": "Strategi implementasi yang dipreferensikan?", "en": "Preferred implementation strategy?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "phased", "label": "Phased (bertahap modul per modul)"},
                        {"value": "big_bang", "label": "Big Bang (semua live bersamaan)"},
                        {"value": "pilot_first", "label": "Pilot dulu di 1 lokasi"},
                        {"value": "no_pref", "label": "Belum ada preferensi"},
                    ],
                    "help": {"id": "Phased = aman tapi lebih lama. Big Bang = cepat tapi risk tinggi.", "en": "Phased = safe but longer. Big Bang = fast but high risk."},
                },
                {
                    "id": "D13-Q04",
                    "prompt": {"id": "Siapa Executive Sponsor untuk proyek ini?", "en": "Who is the Executive Sponsor for this project?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "ceo_owner", "label": "CEO / Owner langsung"},
                        {"value": "director", "label": "Direktur (bukan CEO)"},
                        {"value": "manager", "label": "Manager level"},
                        {"value": "not_yet", "label": "Belum ada / belum ditunjuk"},
                    ],
                    "help": {"id": "Executive Sponsor = decision maker tertinggi yang visible mendukung proyek. KRITIKAL.", "en": "Executive Sponsor = highest decision maker visibly supporting project. CRITICAL."},
                },
                {
                    "id": "D13-Q05",
                    "prompt": {"id": "Tingkat support yang Anda harapkan dari vendor?", "en": "Expected vendor support level?"},
                    "type": "single_choice",
                    "options": [
                        {"value": "247", "label": "24/7 (sangat critical)"},
                        {"value": "business_hours", "label": "Jam kerja (8x5)"},
                        {"value": "best_effort", "label": "Best effort (response < 24 jam)"},
                        {"value": "self_service", "label": "Self-service (documentation + ticketing)"},
                    ],
                    "help": {"id": "SLA Support mempengaruhi harga maintenance.", "en": "Support SLA affects maintenance cost."},
                },
            ],
        },
        {
            "id": "D14",
            "number": 14,
            "code": "additional-notes",
            "title": {"id": "Tambahan & Catatan Akhir", "en": "Additional Notes & Final Remarks"},
            "icon": "MessageSquare",
            "color": "neutral",
            "recommended_pic": ["Semua PIC / Free-form"],
            "estimated_minutes": 5,
            "description": {"id": "Hal-hal lain yang ingin Anda sampaikan namun belum ter-cover di domain sebelumnya.", "en": "Anything else you want to share not covered in previous domains."},
            "questions": [
                {
                    "id": "D14-Q01",
                    "prompt": {"id": "Apakah ada fitur SPESIFIK yang Anda harapkan ada di sistem?", "en": "Any SPECIFIC features you expect in the system?"},
                    "type": "text_long",
                    "help": {"id": "Misal: mobile app untuk owner monitoring, dashboard TV display untuk warehouse.", "en": "E.g.: mobile app for owner monitoring, TV dashboard for warehouse."},
                },
                {
                    "id": "D14-Q02",
                    "prompt": {"id": "Apakah ada KEKHAWATIRAN / RISIKO yang Anda lihat untuk proyek ini?", "en": "Any CONCERNS / RISKS you see for this project?"},
                    "type": "text_long",
                    "help": {"id": "Misal: takut downtime saat go-live, takut tim tidak adopsi, takut data hilang.", "en": "E.g.: fear of downtime at go-live, team resistance, data loss."},
                },
                {
                    "id": "D14-Q03",
                    "prompt": {"id": "Apa kriteria sukses #1 yang membuat Anda akan bilang 'Proyek ini SUKSES BESAR'?", "en": "What is your #1 success criteria for 'This project is a GREAT SUCCESS'?"},
                    "type": "text_long",
                    "help": {"id": "1 kalimat yang menggambarkan outcome ideal di akhir proyek.", "en": "1 sentence describing ideal outcome at project end."},
                },
                {
                    "id": "D14-Q04",
                    "prompt": {"id": "Pertanyaan / hal lain yang ingin Anda tanyakan ke vendor IT?", "en": "Any questions / things you want to ask the IT vendor?"},
                    "type": "text_long",
                    "help": {"id": "Apapun yang ingin Anda klarifikasi. Vendor akan respond di meeting follow-up.", "en": "Anything you want to clarify. Vendor will respond at follow-up meeting."},
                },
            ],
        },
    ],
}


async def seed_kn3_template(db) -> int:
    """Idempotent: seed KN3 ERP & RFID Discovery template. Returns 1 if inserted/updated, 0 if skipped."""
    from datetime import datetime, timezone
    col = db.assessment_templates
    tpl = dict(KN3_TEMPLATE)
    now = datetime.now(timezone.utc).isoformat()
    tpl["updated_at"] = now
    tpl["published"] = True
    # Ensure voided fields present
    if "voided" not in tpl:
        tpl["voided"] = False
    if "created_by" not in tpl:
        tpl["created_by"] = None

    existing = await col.find_one({"id": tpl["id"]})
    if existing:
        await col.replace_one({"id": tpl["id"]}, tpl)
        print(f"[startup] KN3 template updated ({sum(len(d['questions']) for d in tpl['domains'])} questions)")
        return 0
    tpl["created_at"] = now
    await col.insert_one(tpl)
    print(f"[startup] KN3 template inserted ({sum(len(d['questions']) for d in tpl['domains'])} questions)")
    return 1


async def seed():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]
    await seed_kn3_template(db)
    client.close()


if __name__ == "__main__":
    asyncio.run(seed())
