// Test IDs for the admin panel
export const ADMIN = {
  sidebar: 'admin-sidebar',
  dashboard: 'admin-dashboard',
  createButton: 'admin-create-button',
  searchInput: 'admin-search-input',
  table: 'admin-table',
  navDashboard: 'admin-nav-dashboard',
  navLeads: 'admin-nav-leads',
  navUsers: 'admin-nav-users',
  navMedia: 'admin-nav-media',
  navAssessments: 'admin-nav-assessments',
  navAnalytics: 'admin-nav-analytics',
  navSeo: 'admin-nav-seo',
  navNotif: 'admin-nav-notif',
  navDemoSessions: 'admin-nav-demo-sessions',
  navCmsServices: 'admin-nav-cms-services',
  navCmsCases: 'admin-nav-cms-cases',
  navCmsTech: 'admin-nav-cms-tech',
  navCmsTeam: 'admin-nav-cms-team',
  navCmsClients: 'admin-nav-cms-clients',
  navCmsBlog: 'admin-nav-cms-blog',
  navCmsCareers: 'admin-nav-cms-careers',
  navCmsHome: 'admin-nav-cms-home',
  navSettings: 'admin-nav-settings',
  logoutButton: 'admin-logout-button',
  mobileMenuButton: 'admin-mobile-menu-button',
};
