// Test IDs for the client portal feature
export const PORTAL = {
  sidebar: 'portal-sidebar',
  mobileMenuButton: 'portal-mobile-menu-button',
  logoutButton: 'portal-logout-button',
  projectList: 'portal-project-list',
  projectCard: 'portal-project-card',
  projectDetailTab: 'portal-project-detail-tab',
  milestoneList: 'portal-milestone-list',
  milestoneItem: 'portal-milestone-item',
  milestoneAddBtn: 'portal-milestone-add-btn',
  documentList: 'portal-document-list',
  documentUploadBtn: 'portal-document-upload-btn',
  approvalList: 'portal-approval-list',
  approvalRequestBtn: 'portal-approval-request-btn',
  approvalDecideBtn: 'portal-approval-decide-btn',
  threadList: 'portal-thread-list',
  messageList: 'portal-message-list',
  messageInput: 'portal-message-input',
  messageSendBtn: 'portal-message-send-btn',
  invoiceList: 'portal-invoice-list',
  invoiceRow: 'portal-invoice-row',
  adminProjectCreate: 'portal-admin-project-create',
  adminProjectSave: 'portal-admin-project-save',
  adminProjectList: 'portal-admin-project-list',
};
